### ISSUE TITLE
Elastic Search error for large database sizes

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#110]
After reaching about 15GB in size, the Elastic Search DB module fails with an Exception. BITS-Darshini gets restarted; any in-progress analysis gets abandoned.

The application log message is as follows.

```
2017-09-13 20:25:12 INFO  SaveRepository:115 - SaveRepository finished at 1505314512400
2017-09-13 20:25:12 INFO  SaveRepository:103 - Used memory is bytes: 747612544
2017-09-13 20:25:12 INFO  SaveRepository:104 - 1505314512401 Used memory is megabytes: 712
2017-09-13 20:25:12 INFO  SaveRepository:106 - SaveRepository started at 1505314512401 with bucket size: 21
2017-09-13 20:25:15 INFO  SaveRepository:115 - SaveRepository finished at 1505314515587
2017-09-13 20:25:15 INFO  SaveRepository:103 - Used memory is bytes: 771299048
2017-09-13 20:25:15 INFO  SaveRepository:104 - 1505314515587 Used memory is megabytes: 735
2017-09-13 20:25:15 INFO  SaveRepository:106 - SaveRepository started at 1505314515587 with bucket size: 20
2017-09-13 20:25:17 WARN  local:254 - [transport-node] Failed to receive message for action [indices:monitor/stats[s]]
java.lang.NoClassDefFoundError: org/elasticsearch/common/util/concurrent/jsr166e/Striped64$HashCode
	at org.elasticsearch.common.util.concurrent.jsr166e.Striped64$ThreadHashCode.initialValue(Striped64.java:130)
	at org.elasticsearch.common.util.concurrent.jsr166e.Striped64$ThreadHashCode.initialValue(Striped64.java:129)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.elasticsearch.common.util.concurrent.jsr166e.LongAdder.add(LongAdder.java:61)
	at org.elasticsearch.common.util.concurrent.jsr166e.LongAdder.increment(LongAdder.java:73)
	at org.elasticsearch.common.metrics.MeanMetric.inc(MeanMetric.java:32)
	at org.elasticsearch.transport.TransportService$Adapter.received(TransportService.java:344)
	at org.elasticsearch.transport.local.LocalTransport.messageReceived(LocalTransport.java:225)
	at org.elasticsearch.transport.local.LocalTransportChannel$1.run(LocalTransportChannel.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.common.util.concurrent.jsr166e.Striped64$HashCode
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1858)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1701)
	... 13 more
2017-09-13 20:25:18 WARN  engine:458 - [transport-node] [protocol_session_-1343965793][0] failed engine [refresh failed]
java.io.FileNotFoundException: /home/vikram/Darshini/darshini-es/data/protocol-analyzer/nodes/0/indices/protocol_session_-1343965793/0/index/_4
s.nvd (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:384)
	at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:277)
	at org.apache.lucene.store.FileSwitchDirectory.createOutput(FileSwitchDirectory.java:152)
	at org.apache.lucene.store.RateLimitedFSDirectory.createOutput(RateLimitedFSDirectory.java:40)
	at org.apache.lucene.store.FilterDirectory.createOutput(FilterDirectory.java:69)
	at org.apache.lucene.store.FilterDirectory.createOutput(FilterDirectory.java:69)
	at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:44)
	at org.apache.lucene.codecs.lucene49.Lucene49NormsConsumer.<init>(Lucene49NormsConsumer.java:56)
	at org.apache.lucene.codecs.lucene49.Lucene49NormsFormat.normsConsumer(Lucene49NormsFormat.java:107)
	at org.apache.lucene.index.DefaultIndexingChain.writeNorms(DefaultIndexingChain.java:196)
	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:94)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:441)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:521)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:632)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:410)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:297)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:272)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:262)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:171)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:118)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:568)
	at org.elasticsearch.index.engine.InternalEngine$1.run(InternalEngine.java:387)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-09-13 20:25:18 WARN  cluster:871 - [transport-node] [[protocol_session_-1343965793][0]] marking and sending shard failed due to [engine fa
ilure, reason [refresh failed]]
java.io.FileNotFoundException: /home/vikram/Darshini/darshini-es/data/protocol-analyzer/nodes/0/indices/protocol_session_-1343965793/0/index/_4
s.nvd (Too many open files)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:384)
	at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:277)
	at org.apache.lucene.store.FileSwitchDirectory.createOutput(FileSwitchDirectory.java:152)
	at org.apache.lucene.store.RateLimitedFSDirectory.createOutput(RateLimitedFSDirectory.java:40)
	at org.apache.lucene.store.FilterDirectory.createOutput(FilterDirectory.java:69)
	at org.apache.lucene.store.FilterDirectory.createOutput(FilterDirectory.java:69)
	at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:44)
	at org.apache.lucene.codecs.lucene49.Lucene49NormsConsumer.<init>(Lucene49NormsConsumer.java:56)
	at org.apache.lucene.codecs.lucene49.Lucene49NormsFormat.normsConsumer(Lucene49NormsFormat.java:107)
	at org.apache.lucene.index.DefaultIndexingChain.writeNorms(DefaultIndexingChain.java:196)
	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:94)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:441)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:521)
	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:632)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:410)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:297)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:272)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:262)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:171)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:118)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:568)
	at org.elasticsearch.index.engine.InternalEngine$1.run(InternalEngine.java:387)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-09-13 20:25:18 WARN  shard:137 - [transport-node] [protocol_session_-1343965793][0] received shard failed for [protocol_session_-134396579
3][0], node[xiZPdZE0R-uqxPIHGv4rIg], [P], s[STARTED], indexUUID [AMYy6jcqQIKHyotLFpxeTQ], reason [shard failure [engine failure, reason [refres
h failed]][FileNotFoundException[/home/vikram/Darshini/darshini-es/data/protocol-analyzer/nodes/0/indices/protocol_session_-1343965793/0/index/
_4s.nvd (Too many open files)]]]
2017-09-13 21:39:47 WARN  transport:419 - [transport-node] Transport response handler not found of id [25256]
2017-09-13 22:30:18 WARN  transport:419 - [transport-node] Transport response handler not found of id [40675]
2017-09-13 22:38:35 INFO  XmlWebApplicationContext:862 - Closing WebApplicationContext for namespace 'spring-servlet': startup date [Wed Sep 13
 20:16:45 IST 2017]; parent: Root WebApplicationContext
2017-09-13 22:38:35 INFO  XmlWebApplicationContext:862 - Closing Root WebApplicationContext: startup date [Wed Sep 13 20:16:14 IST 2017]; root 
of context hierarchy
2017-09-13 22:38:49 INFO  ContextLoader:285 - Root WebApplicationContext: initialization started
2017-09-13 22:38:50 INFO  XmlWebApplicationContext:510 - Refreshing Root WebApplicationContext: startup date [Wed Sep 13 22:38:50 IST 2017]; ro
ot of context hierarchy
2017-09-13 22:38:50 INFO  XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [spring/appconfig.xml]
2017-09-13 22:38:50 INFO  XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [spring/mvc-config.xml]
2017-09-13 22:38:51 INFO  node:141 - [transport-node] version[1.5.2], pid[8804], build[62ff986/2015-04-27T09:21:06Z]
2017-09-13 22:38:51 INFO  node:143 - [transport-node] initializing ...
2017-09-13 22:38:51 INFO  plugins:151 - [transport-node] loaded [], sites []
2017-09-13 22:38:54 INFO  node:213 - [transport-node] initialized
```

**Comment by prasadtalasila** [comment]
The only hope is to upgrade to the latest elastic stack.
